zip -r ~/phemex-$(date +%F).zip . \
  -x "node_modules/*" \
  -x ".git/*" \
  -x "php-ticker/vendor/*" \
  -x "rust-ticker/target/*" \
  -x "csharp-ticker/obj/*" \
  -x "kt-ticker/build/*" \
  -x "kt-ticker/.gradle/*" \
  -x "kt-ticker/gradle/*" \
  -x "ts-ticker/node_modules/*" \
  -x "cpp-ticker/build/*" \
  -x "cpp-ticker/deps/*" \
  -x "java-ticker/build/*" \
  -x "java-ticker/.gradle/*" \
  -x "java-ticker/gradle/*" \
  -x "java-ticker/bin/*" \
  -x ".github/*" \
  -x "csharp-ticker/bin/*"
